version: '3.8'

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx_static
    ports:
      - "8081:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
    restart: unless-stopped
